version: "3.9"
name: instagram-clone
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  mongo:
    image: mongo:6.0.5
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017